### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by rtaeho** [CafeInCode-Sejong/CafeInCode_Backend#6]
## 📄 설명
네이버 및 카카오의 소셜로그인 구현
---

## ✅ TO-DO-LIST
해야 할 작업을 체크박스 형태로 작성해 주세요.
- [x] 구글 클라우드 프로젝트 생성
- [x] 구글 OAuth 설정 및 클라이언트 ID 발급
- [ ] 네이버 개발자 센터 애플리케이션 등록
- [ ] 네이버 OAuth 설정 및 클라이언트 ID 발급
- [ ] 깃 추적 금지 설정
- [ ] 스프링 application.properties에 키 추가
- [ ] 구글 로그인 구현
- [ ] 네이버 로그인 구현
---

## 고민해볼 점
~~postman으로 google oauth api 테스트 중 401 에러와 실패~~  
-> 클라이언트 아이디 잘못 입력
---

## 🙋🏻 참고 자료
[[SpringBoot] - 구글, 네이버 소셜로그인 구현 설정](https://jay-cheol.tistory.com/256)
[Spring Security Oauth2.0 소셜 로그인(kakao, naver, google)](https://velog.io/@gmldus0008/Spring-Boot-Oauth2.0-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8kakao-naver-google)
[github 커밋 히스토리에서 application.yml, application.properties 같은 중요파일 모두 삭제하기](https://velog.io/@mk020/github-%EC%BB%A4%EB%B0%8B-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%97%90%EC%84%9C-application.yml-application.properties-%EA%B0%99%EC%9D%80-%EC%A4%91%EC%9A%94%ED%8C%8C%EC%9D%BC-%EB%AA%A8%EB%91%90-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0)
[구글 소셜 로그인 설정](https://velog.io/@gmlstjq123/%EA%B5%AC%EA%B8%80-%EC%86%8C%EC%85%9C%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84)
